image: node:14.19.0 # change to match your node version

cache:
  paths:
    - work/node_modules/
    - cache/dev
    - cache/main

before_script:
  - echo "//gitlab.com/api/v4/projects/24337530/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
  - npm install
  - npm run postinstall

#test:
#  stage: test
#  script:
#   - CI=true npm test

#lint:
#  stage: test
#  script:
#    - npm run lint

pages:
  environment: production
  stage: deploy
  script:
    - DIR="$CI_COMMIT_BRANCH"
    - ls 
    - ls public
    - mkdir work
    - shopt -s extglob
    - mv !(work|cache) work
    - mkdir -p cache
    - mkdir -p public
    - cp -R cache/* public
    - ls 
    - ls cache
    - ls public
    - cd work
    - ls
    - ls public
    - CI=false npm run build
    - rm -rf ../public/$DIR
    - mv build ../public/$DIR
    - rm -rf ../cache/$DIR
    - mkdir -p ../cache/$DIR
    - cp ../public/$DIR/* ../cache/$DIR

  artifacts:
    paths:
      - public # GitLab pages serve from a 'public' directory
    expire_in: '900'
  only:
    - dev
    - main
